### ISSUE TITLE
Error compiling with esp8266 board package 2.4.0

### ISSUE THREAD

**Issue by pyro2k8** [grzesl/ESPMail#4]
Trying to compile the example mail_send the compiler has this error:
```
C:\Users\anonymous\AppData\Local\Temp\arduino_build_962164/arduino.ar(libc_replacements.c.o): In function `_putc_r:

C:\Users\anonymous\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0\cores\esp8266/libc_replacements.c:96: multiple definition of `_putc_r'

C:\Users\anonymous\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.4.0/tools/sdk/libc/xtensa-lx106-elf/lib\libc.a(lib_a-putc.o):/Users/igrokhotkov/e/newlib-xtensa/xtensa-lx106-elf/newlib/libc/stdio/../../../.././newlib/libc/stdio/putc.c:97: first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Fehler beim Kompilieren für das Board SparkFun ESP8266 Thing Dev.
```

**Comment by grzesl** [comment]
try this:

the line |#include "libquickmail\quickmail.h"| should be changed to 
|#include "libquickmail/quickmail.h"| (slash error).

W dniu 2018-01-27 o 08:33, pyro2k8 pisze:

**Comment by pyro2k8** [comment]
I have changed the line `#include "libquickmail\quickmail.h"  to #include "libquickmail/quickmail.h"` in ESPMail.h.
Same error occuring with multiple definitions of _putc_r when compiling the sketch.

Some more informations:
- Arduino version is 1.8.5
- ESPMail lib version is 1.0.2
- ESP core (board library) is 2.4.0

The sketch is just this:

```
#include <ESP8266WiFi.h>  //same with #include <WiFi.h>
#include "ESPMail.h"                            

void setup()
{    
}

void loop()
{   
}
```

Everything works fine with ESP core (board version) 2.3.0!

**Comment by trlafleur** [comment]
I have the same issue, work fine for ESP32 and ARM M0 processors
Issue looks to be in the ESP core (board library) is 2.4.0 and 2.4.1

**Comment by DanielOgorchock** [comment]
I ran into the same issue and am using this workaround:

A _putc_r definition is found on line 96 of packages/esp8266/hardware/esp8266/2.4.1/cores/esp8266/libc_replacements.c

Simply commenting it out allowed me to compile.
